default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: dev
  username: dev
  password: dev
  port: 5437
  <<: *default

test:
  <<: *default
  host: localhost
  database: dev
  username: dev
  password: dev
  port: 5437
  <<: *default

production:
  <<: *default
  database: leiva_investing_production
  username: leiva_investing
  password: <%= ENV["LEIVA_INVESTING_DATABASE_PASSWORD"] %>
